#!/bin/sh
#This will cause the script to exit immediately if a command exits with a nonzero exit value (for pipes is not enough)

set -e
echo "Running pre-commit hook"
# Custom
tox -c tox.ini --root components/component1/ -- -m "not slow"
tox -c tox.ini --root components/component2/ -- -m "not slow"
tox -c tox.ini --root components/component3/ -- -m "not slow"
tox -c tox.ini --root components/component4/ -- -m "not slow"