[project]
name = "component4"
version = "1.0.0"
description = "The component 4"
requires-python = ">=3.10"

dependencies = [
    "redis == 5.0.1"
]

[build-system]
requires = ["setuptools>=68.0", "wheel"]