[project]
name = "component2"
version = "1.0.0"
description = "The component 2"
requires-python = ">=3.10"

dependencies = [
    "numpy == 1.26"
]

[build-system]
requires = ["setuptools>=68.0", "wheel"]